version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ls-dtools:latest
    container_name: ls-dtools
    ports:
      - 8080:80
    volumes:
      - .:/web/app
