version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ls-dtools:latest
    container_name: ls-dtools
    ports:
      - 7331:80
    volumes:
      - .:/web/app

networks:
  default:
    external:
      name: lightspeed
